{
 "title": "WebApp站点",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "告警状态",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ALERTS{alertname=\"WebAppServiceDown\",alertstate=\"firing\"}",
     "legendFormat": "服务宕机告警"
    }
   ]
  },
  {
   "title": "服务可用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{service=\"webApp\"})/count(up{service=\"webApp\"}) * 100",
     "legendFormat": "可用率"
    }
   ]
  },
  {
   "title": "服务数量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(instance) (up{service=\"webApp\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "count(up{service=\"webApp\"})",
     "legendFormat": "webApp站点总数量"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(dotnet_process_cpu_time_seconds_total{job=\"webApp\"}[5m])) * 100",
     "legendFormat": "{{instance}}-CPU使用率"
    }
   ]
  },
  {
   "title": "内存（MB）",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "dotnet_process_memory_working_set_bytes{job=\"webApp\"} / 1000000",
     "legendFormat": "{{instance}}-物理内存使用量"
    }
   ]
  },
  {
   "title": "线程",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "process_thread_count{job=\"webApp\"}",
     "legendFormat": "{{instance}}-活跃线程数"
    },
    {},
    {
     "expr": "max_over_time(process_thread_count{job=\"webApp\"}[1h])",
     "legendFormat": "{{instance}}-线程峰值"
    }
   ]
  },
  {
   "title": "堆内存使用量（MB）",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(instance, gc_heap_generation) (dotnet_gc_last_collection_heap_size_bytes{job=\"webApp\"}) / 1000000",
     "legendFormat": "{{instance}}-{{gc_heap_generation}}堆内存使用量"
    }
   ]
  },
  {
   "title": "堆碎片量（MB）",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum by(instance, gc_heap_generation) (dotnet_gc_last_collection_heap_fragmentation_size_bytes{job=\"webApp\"}) / 1000000",
     "legendFormat": "{{instance}}-{{gc_heap_generation}}堆碎片量"
    }
   ]
  },
  {
   "title": "异常",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(error_type, instance) (dotnet_exceptions_total{job=\"webApp\"})",
     "legendFormat": "{{instance}}-{{error_type}}"
    }
   ]
  },
  {
   "title": "锁竞争",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "increase(dotnet_monitor_lock_contentions_total{job=\"webApp\"}[5m])",
     "legendFormat": "{{instance}}-{{gc_heap_generation}}锁竞争"
    }
   ]
  },
  {
   "title": "GC暂停时间（微秒）",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(dotnet_gc_pause_time_seconds_total{job=\"webApp\"}[5m])) by (instance) * 1000000",
     "legendFormat": "{{instance}}-GC总暂停时间（微秒）"
    }
   ]
  }
 ]
}