version: '3.8'
name: "eshopcopy"
services:
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Shanghai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - prometheus
    environment:
      TZ: Asia/Shanghai
    networks:
      - monitoring
    volumes:
      - grafana_data:/var/lib/grafana
      - ../monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ../monitoring/grafana/dashboards:/etc/grafana/dashboards
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "${GRAFANA_URL}:${GRAFANA_PORT}/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../monitoring/prometheus/prometheus.${ENV}.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - monitoring
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "${PROMETHEUS_URL}:${PROMETHEUS_PORT}/-/healthy" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge