global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'webApp'
    static_configs:
      - targets: ['host.docker.internal:7308']
        labels:
          service: 'webApp'
          team: 'frontend'
    scheme: https
    tls_config:
      insecure_skip_verify: true