global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'webApp'
    static_configs:
      - targets: ['host.docker.internal:5055']
        labels:
          service: 'webApp'
          team: 'frontend'